### ISSUE TITLE
macOSでコンパイルできません

### ISSUE THREAD

**Issue by uchkw** [samn33/qlazy#1]
macOSサポートされていないのにissueを上げてしまい恐縮です．
macOSのファイルシステムは（通常）大文字と小文字を区別しないため，Ubuntuであれば"cmake .."後にCMakeFiles以下に作成される qlazy.dir と Qlazy.dir が，macOSでは作成されず（qlazy.dirのみ）, make途中でエラーとなります．ご解決いただけると非常に幸いです．
よろしくおねがいいたします．

**Comment by samn33** [comment]
ご指摘いただき、ありがとうございます！
当方、MacOSのテスト環境かないため確認できませんが、エラーの内容は理解しました。次回(近日)予定しているバージョンアップで、できれば対応したいと思います。相変わらずMacOSでのテストはできないので、対応したつもり版になりますが、、
いましばらくお待ちください。

**Comment by samn33** [comment]
v0.0.35で対応しました(つもりです)。ライブラリの名前をlibQlazy.soからlibqlz.soに変更しました。

**Comment by uchkw** [comment]
修正ありがとうございます．
macOS Mojave ver. 10.14.6 でコンパイル完了し，
README.md記述のサンプルプログラムが正常に動作することを確認しました．
ご対応ありがとうございました．
