### ISSUE TITLE
OSError: dlopen(libqlz.so, 10): image not found on macOS 10.14.6

### ISSUE THREAD

**Issue by uchkw** [samn33/qlazy#2]
macOSの動的ライブラリの拡張子は '.so' ではなく，'.dylib' のため，現バージョン(0.0.35)ではqlazypyの実行時にライブラリの読み込みに失敗します．

一時的に以下の4つのファイルで
- 	py/qlazypy/DensOp.py
- 	py/qlazypy/MData.py
- 	py/qlazypy/Observable.py
- 	py/qlazypy/QState.py

ライブラリ読み込み部分を以下のように書き換えることで，macOSでも正常にqlazypyが動作することを確認しました．
```python
def get_lib_ext():

    import platform
    if platform.system() == 'Darwin':
        return 'dylib'
    else:
        return 'so'

lib = ctypes.CDLL('libqlz.'+get_lib_ext(),mode=ctypes.RTLD_GLOBAL)
```

ご対応よろしくお願いいたします．

**Comment by samn33** [comment]
お知らせいただき、ありがとうございます！そして、お手数おかけしました。複数OS対応は考えていなかったので、抜けていました。platformモジュールを使えば簡単ですね。次回のバージョンアップで対応したいと思います。

**Comment by samn33** [comment]
v0.0.36で対応しました(つもりです)。util.pyにplatform判定関数を入れました。

**Comment by uchkw** [comment]
早速のご対応ありがとうございます．
v0.0.36 で解決していることを確認しました．
